### GET request to example server
PUT http://localhost:8080/api/creator/courses/9958b9f2-253b-4ab1-aa55-067b6d64a1de
Content-Type: multipart/form-data

{
  "courseTitle": "Introduction to Programming 2",
  "subTitle": "Intermediate Programming Concepts",
  "category": "Programming - Web Development",
  "description": "A intermediate course on programming concepts.",
  "price": 29.99,
  "courseLevel": "MEDIUM"
}